name: Publish .NET Tool

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Blueflow.Chopper/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Publish via Betalgo-Nuget-Publisher
      uses: betalgo/NugetPublisher@v1.1.0
      with:
        project-file: 'Blueflow.Chopper/Blueflow.Chopper.csproj'
        package-name: 'Betalgo.Blueflow.Chopper'
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        dotnet-version: '10.0.x'
        tag-commit: true
